import { createContext, useContext, useState, ReactNode } from "react";

type Lang = "en" | "es";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const translations: Record<Lang, Record<string, string>> = {
  en: {
    // Navbar
    "nav.howItWorks": "How it works",
    "nav.pricing": "Pricing",
    "nav.faq": "FAQ",
    "nav.login": "Sign in",
    "nav.cta": "Get started free",

    // Hero
    "hero.badge": "🗺️ Powered by Google Maps + Apify",
    "hero.headline1": "Find customers in",
    "hero.headline2": "any city",
    "hero.headline3": "in the world",
    "hero.subheadline": "Extract leads from Google Maps with name, phone, address, website and email in minutes. No code. No geographic limits.",
    "hero.stat1": "Businesses indexed",
    "hero.stat2": "Countries available",
    "hero.stat3": "Scraping time",
    "hero.cta1": "Get started free",
    "hero.cta2": "See how it works",
    "hero.cardCompleted": "Search completed",
    "hero.cardLeads": "leads found",
    "hero.lead": "Lead",

    // Problem
    "problem.title1": "The problem with",
    "problem.title2": "traditional prospecting",
    "problem.subtitle": "Companies waste weeks searching for leads manually. MapLeads solves it in minutes.",
    "problem.withoutTitle": "Without MapLeads",
    "problem.withTitle": "With MapLeads",
    "problem.p1": "Outdated and expensive lead lists",
    "problem.p2": "Incomplete data: no phone or website",
    "problem.p3": "Limited geographic coverage",
    "problem.p4": "Manual scraping that takes hours",
    "problem.p5": "Per-lead pricing that inflates costs",
    "problem.s1": "Real-time data from Google Maps",
    "problem.s2": "Name, phone, website and email included",
    "problem.s3": "195+ countries with no geographic restrictions",
    "problem.s4": "Results ready in less than 5 minutes",
    "problem.s5": "Flat plans with thousands of leads included",

    // How it works
    "how.title1": "How it works",
    "how.title2": "in 3 steps",
    "how.subtitle": "No installations, no code, no hassle. Start generating leads in minutes.",
    "how.step1.title": "Define your search",
    "how.step1.desc": "Enter the keyword, city and country. For example: 'restaurants', 'Barcelona', 'Spain'. MapLeads does the rest.",
    "how.step2.title": "Automatic extraction",
    "how.step2.desc": "Our Apify-powered engine analyzes Google Maps and extracts all available data: name, phone, website, address, reviews.",
    "how.step3.title": "Export and act",
    "how.step3.desc": "Download your leads in CSV with one click. Use them in your CRM, email marketing, or call your prospects directly.",

    // Pricing
    "pricing.title1": "Simple and",
    "pricing.title2": "transparent pricing",
    "pricing.subtitle": "No hidden fees. Pay for the plan you need and scale whenever you want.",
    "pricing.popular": "Most popular",
    "pricing.perMonth": "/month",
    "pricing.leadsMonth": "leads/month",
    "pricing.footer": "💳 Secure payment via Stripe · No contracts · Cancel anytime",
    "pricing.starter.desc": "Perfect for freelancers and small agencies.",
    "pricing.starter.f1": "2,000 leads per month",
    "pricing.starter.f2": "Unlimited searches",
    "pricing.starter.f3": "CSV export",
    "pricing.starter.f4": "Data: name, phone, website, address",
    "pricing.starter.f5": "Email support",
    "pricing.starter.cta": "Start with Starter",
    "pricing.growth.desc": "For expanding sales teams.",
    "pricing.growth.f1": "5,000 leads per month",
    "pricing.growth.f2": "Everything in Starter",
    "pricing.growth.f3": "✉️ Email enrichment included",
    "pricing.growth.f4": "Full search history",
    "pricing.growth.f5": "Priority support",
    "pricing.growth.cta": "Start with Growth",
    "pricing.pro.desc": "For agencies and advanced teams.",
    "pricing.pro.f1": "15,000 leads per month",
    "pricing.pro.f2": "Everything in Growth",
    "pricing.pro.f3": "🔄 Automatic recurring searches",
    "pricing.pro.f4": "API access (coming soon)",
    "pricing.pro.f5": "Dedicated support",
    "pricing.pro.cta": "Start with Pro",

    // FAQ
    "faq.title1": "Frequently",
    "faq.title2": "asked questions",
    "faq.q1": "Where does the data come from?",
    "faq.a1": "MapLeads uses Apify to extract public data from Google Maps. All data is publicly accessible and obtained in compliance with applicable terms of service.",
    "faq.q2": "Is it legal to use MapLeads?",
    "faq.a2": "Yes. MapLeads extracts publicly available information from Google Maps (name, address, phone, website). The use of data for commercial contact is subject to privacy laws of each country (GDPR, CCPA, etc.). The user is responsible for how they use the obtained data.",
    "faq.q3": "How long does a search take?",
    "faq.a3": "Most searches complete in 2-5 minutes depending on the number of results requested and service availability.",
    "faq.q4": "What does email enrichment include?",
    "faq.a4": "Growth and Pro plans include email extraction from the websites of the businesses found. It is an additional process that scans web pages for contact email addresses.",
    "faq.q5": "Can I cancel my subscription?",
    "faq.a5": "Yes, you can cancel at any time from your dashboard. You will retain access until the end of the current billing period.",
    "faq.q6": "Do leads reset every month?",
    "faq.a6": "Yes. The leads_used counter resets automatically every month at the start of the new billing period. Previously stored leads are kept.",
    "faq.q7": "How are payments processed?",
    "faq.a7": "All payments are processed securely through Stripe. We do not store credit card data on our servers.",

    // CTA
    "cta.title1": "Start generating leads",
    "cta.title2": "today",
    "cta.subtitle": "Join hundreds of sales teams already using MapLeads to find new customers every day.",
    "cta.btn": "Get started now",
    "cta.footer": "No credit card required · Cancel anytime",

    // Footer
    "footer.rights": "© 2025 MapLeads · All rights reserved",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",

    // Auth
    "auth.back": "Back to home",
    "auth.login": "Sign in",
    "auth.register": "Create account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Full name",
    "auth.namePlaceholder": "Your name",
    "auth.passwordPlaceholder": "Minimum 6 characters",
    "auth.loginBtn": "Sign in",
    "auth.loginLoading": "Signing in...",
    "auth.registerBtn": "Create free account",
    "auth.registerLoading": "Creating account...",
    "auth.terms1": "By registering you accept our",
    "auth.termsLink": "Terms of service",
    "auth.terms2": "and",
    "auth.privacyLink": "Privacy policy",
    "auth.loginError": "Sign in error",
    "auth.registerSuccess": "Account created!",
    "auth.registerSuccessDesc": "Check your email to confirm your account.",
    "auth.registerError": "Registration error",

    // Dashboard
    "dash.title": "Dashboard",
    "dash.subtitle": "Manage your searches and leads",
    "dash.newSearch": "New search",
    "dash.searches": "Searches",
    "dash.leadsUsed": "Leads used",
    "dash.upgradeBtn": "Upgrade plan",
    "dash.signOut": "Sign out",
    "dash.emptyTitle": "No searches yet",
    "dash.emptyCreate": "Create first search",
    "dash.keyword": "Keyword",
    "dash.keywordPlaceholder": "e.g: restaurants, dentists, lawyers...",
    "dash.city": "City",
    "dash.cityPlaceholder": "e.g: Barcelona",
    "dash.country": "Country",
    "dash.countryPlaceholder": "e.g: Spain",
    "dash.maxResults": "Max results",
    "dash.quotaAvailable": "Available quota",
    "dash.startSearch": "Start search",
    "dash.starting": "Starting...",
    "dash.cancel": "Cancel",
    "dash.exportCsv": "Export CSV",
    "dash.welcomeTitle": "Welcome to MapLeads",
    "dash.welcomeDesc": "Create your first search to extract leads from Google Maps in any city in the world.",
    "dash.createFirst": "Create first search",
    "dash.noResults": "No results",
    "dash.noResultsDesc": "No businesses found for this search.",
    "dash.statusQueued": "Queued",
    "dash.statusRunning": "Running",
    "dash.statusCompleted": "Completed",
    "dash.statusFailed": "Failed",
    "dash.statusQueuedDesc": "The search is queued, it will start soon.",
    "dash.statusRunningDesc": "Scraping is in progress, wait a few minutes.",
    "dash.statusFailedDesc": "The search failed. Please try again.",
    "dash.colName": "Business",
    "dash.colCategory": "Category",
    "dash.colPhone": "Phone",
    "dash.colWebsite": "Website",
    "dash.colEmail": "Email",
    "dash.colRating": "Rating",
    "dash.quotaError": "Quota exhausted",
    "dash.quotaErrorDesc": "You have reached your plan's lead limit.",
    "dash.searchCreated": "Search created!",
    "dash.searchCreatedDesc": "Scraping has started.",
    "dash.searchError": "Error",
    "dash.searchErrorDesc": "Could not create the search.",
    "dash.apifyNotConfigured": "Connect to Apify to activate automatic scraping.",
    "dash.newSearchTitle": "New search",
  },
  es: {
    // Navbar
    "nav.howItWorks": "Cómo funciona",
    "nav.pricing": "Precios",
    "nav.faq": "FAQ",
    "nav.login": "Iniciar sesión",
    "nav.cta": "Comenzar gratis",

    // Hero
    "hero.badge": "🗺️ Powered by Google Maps + Apify",
    "hero.headline1": "Encuentra clientes en",
    "hero.headline2": "cualquier ciudad",
    "hero.headline3": "del mundo",
    "hero.subheadline": "Extrae leads de Google Maps con nombre, teléfono, dirección, web y email en minutos. Sin código. Sin límites geográficos.",
    "hero.stat1": "Negocios indexados",
    "hero.stat2": "Países disponibles",
    "hero.stat3": "Tiempo de scraping",
    "hero.cta1": "Empezar gratis",
    "hero.cta2": "Ver cómo funciona",
    "hero.cardCompleted": "Búsqueda completada",
    "hero.cardLeads": "leads encontrados",
    "hero.lead": "Lead",

    // Problem
    "problem.title1": "El problema con la",
    "problem.title2": "prospección tradicional",
    "problem.subtitle": "Las empresas pierden semanas buscando leads manualmente. MapLeads lo resuelve en minutos.",
    "problem.withoutTitle": "Sin MapLeads",
    "problem.withTitle": "Con MapLeads",
    "problem.p1": "Listas de leads desactualizadas y costosas",
    "problem.p2": "Datos incompletos: sin teléfono ni web",
    "problem.p3": "Cobertura geográfica limitada",
    "problem.p4": "Scraping manual que tarda horas",
    "problem.p5": "Precios por lead individuales que disparan costos",
    "problem.s1": "Datos en tiempo real desde Google Maps",
    "problem.s2": "Nombre, teléfono, web y email incluidos",
    "problem.s3": "195+ países sin restricciones geográficas",
    "problem.s4": "Resultados listos en menos de 5 minutos",
    "problem.s5": "Planes planos con miles de leads incluidos",

    // How it works
    "how.title1": "Cómo funciona",
    "how.title2": "en 3 pasos",
    "how.subtitle": "Sin instalaciones, sin código, sin complicaciones. Empieza a generar leads en minutos.",
    "how.step1.title": "Define tu búsqueda",
    "how.step1.desc": "Introduce la keyword, ciudad y país. Por ejemplo: 'restaurantes', 'Barcelona', 'España'. MapLeads hace el resto.",
    "how.step2.title": "Extracción automática",
    "how.step2.desc": "Nuestro motor basado en Apify analiza Google Maps y extrae todos los datos disponibles: nombre, teléfono, web, dirección, reseñas.",
    "how.step3.title": "Exporta y actúa",
    "how.step3.desc": "Descarga tus leads en CSV con un clic. Úsalos en tu CRM, email marketing o llama directamente a tus prospectos.",

    // Pricing
    "pricing.title1": "Planes simples y",
    "pricing.title2": "transparentes",
    "pricing.subtitle": "Sin costos ocultos. Paga por el plan que necesitas y escala cuando quieras.",
    "pricing.popular": "Más popular",
    "pricing.perMonth": "/mes",
    "pricing.leadsMonth": "leads/mes",
    "pricing.footer": "💳 Pago seguro con Stripe · Sin contrato · Cancela cuando quieras",
    "pricing.starter.desc": "Perfecto para freelancers y pequeñas agencias.",
    "pricing.starter.f1": "2.000 leads por mes",
    "pricing.starter.f2": "Búsquedas ilimitadas",
    "pricing.starter.f3": "Exportar CSV",
    "pricing.starter.f4": "Datos: nombre, teléfono, web, dirección",
    "pricing.starter.f5": "Soporte por email",
    "pricing.starter.cta": "Empezar con Starter",
    "pricing.growth.desc": "Para equipos de ventas en expansión.",
    "pricing.growth.f1": "5.000 leads por mes",
    "pricing.growth.f2": "Todo lo del plan Starter",
    "pricing.growth.f3": "✉️ Email enrichment incluido",
    "pricing.growth.f4": "Historial completo de búsquedas",
    "pricing.growth.f5": "Soporte prioritario",
    "pricing.growth.cta": "Empezar con Growth",
    "pricing.pro.desc": "Para agencias y equipos avanzados.",
    "pricing.pro.f1": "15.000 leads por mes",
    "pricing.pro.f2": "Todo lo del plan Growth",
    "pricing.pro.f3": "🔄 Búsquedas recurrentes automáticas",
    "pricing.pro.f4": "API access (próximamente)",
    "pricing.pro.f5": "Soporte dedicado",
    "pricing.pro.cta": "Empezar con Pro",

    // FAQ
    "faq.title1": "Preguntas",
    "faq.title2": "frecuentes",
    "faq.q1": "¿De dónde provienen los datos?",
    "faq.a1": "MapLeads utiliza Apify para extraer datos públicos de Google Maps. Todos los datos son de acceso público y se obtienen respetando los términos de uso aplicables.",
    "faq.q2": "¿Es legal usar MapLeads?",
    "faq.a2": "Sí. MapLeads extrae información públicamente disponible en Google Maps (nombre, dirección, teléfono, web). El uso de los datos para contacto comercial está sujeto a las leyes de privacidad de cada país (GDPR, CCPA, etc.). El usuario es responsable del uso que hace de los datos obtenidos.",
    "faq.q3": "¿Cuánto tiempo tarda una búsqueda?",
    "faq.a3": "La mayoría de búsquedas se completan en 2-5 minutos dependiendo del número de resultados solicitados y la disponibilidad del servicio.",
    "faq.q4": "¿Qué incluye el email enrichment?",
    "faq.a4": "Los planes Growth y Pro incluyen extracción de emails desde las webs de los negocios encontrados. Es un proceso adicional que escanea las páginas web en busca de direcciones de contacto.",
    "faq.q5": "¿Puedo cancelar mi suscripción?",
    "faq.a5": "Sí, puedes cancelar en cualquier momento desde tu dashboard. Mantendrás acceso hasta el final del período de facturación actual.",
    "faq.q6": "¿Los leads se resetean cada mes?",
    "faq.a6": "Sí. El contador de leads_used se resetea automáticamente cada mes al inicio del nuevo período de facturación. Los leads almacenados anteriormente se mantienen.",
    "faq.q7": "¿Cómo se procesan los pagos?",
    "faq.a7": "Todos los pagos se procesan de forma segura a través de Stripe. No almacenamos datos de tarjetas de crédito en nuestros servidores.",

    // CTA
    "cta.title1": "Empieza a generar leads",
    "cta.title2": "hoy mismo",
    "cta.subtitle": "Únete a cientos de equipos de ventas que ya usan MapLeads para encontrar nuevos clientes cada día.",
    "cta.btn": "Comenzar ahora",
    "cta.footer": "Sin tarjeta de crédito para comenzar · Cancela cuando quieras",

    // Footer
    "footer.rights": "© 2025 MapLeads · Todos los derechos reservados",
    "footer.privacy": "Privacidad",
    "footer.terms": "Términos",

    // Auth
    "auth.back": "Volver al inicio",
    "auth.login": "Iniciar sesión",
    "auth.register": "Crear cuenta",
    "auth.email": "Email",
    "auth.password": "Contraseña",
    "auth.name": "Nombre completo",
    "auth.namePlaceholder": "Tu nombre",
    "auth.passwordPlaceholder": "Mínimo 6 caracteres",
    "auth.loginBtn": "Iniciar sesión",
    "auth.loginLoading": "Iniciando sesión...",
    "auth.registerBtn": "Crear cuenta gratis",
    "auth.registerLoading": "Creando cuenta...",
    "auth.terms1": "Al registrarte aceptas nuestros",
    "auth.termsLink": "Términos de servicio",
    "auth.terms2": "y",
    "auth.privacyLink": "Política de privacidad",
    "auth.loginError": "Error al iniciar sesión",
    "auth.registerSuccess": "¡Cuenta creada!",
    "auth.registerSuccessDesc": "Revisa tu email para confirmar tu cuenta.",
    "auth.registerError": "Error al registrarse",

    // Dashboard
    "dash.title": "Dashboard",
    "dash.subtitle": "Gestiona tus búsquedas y leads",
    "dash.newSearch": "Nueva búsqueda",
    "dash.searches": "Búsquedas",
    "dash.leadsUsed": "Leads usados",
    "dash.upgradeBtn": "Actualizar plan",
    "dash.signOut": "Cerrar sesión",
    "dash.emptyTitle": "Aún no tienes búsquedas",
    "dash.emptyCreate": "Crear primera búsqueda",
    "dash.keyword": "Keyword",
    "dash.keywordPlaceholder": "ej: restaurantes, dentistas, abogados...",
    "dash.city": "Ciudad",
    "dash.cityPlaceholder": "ej: Barcelona",
    "dash.country": "País",
    "dash.countryPlaceholder": "ej: España",
    "dash.maxResults": "Máximo resultados",
    "dash.quotaAvailable": "Cuota disponible",
    "dash.startSearch": "Iniciar búsqueda",
    "dash.starting": "Iniciando...",
    "dash.cancel": "Cancelar",
    "dash.exportCsv": "Exportar CSV",
    "dash.welcomeTitle": "Bienvenido a MapLeads",
    "dash.welcomeDesc": "Crea tu primera búsqueda para extraer leads de Google Maps de cualquier ciudad del mundo.",
    "dash.createFirst": "Crear primera búsqueda",
    "dash.noResults": "Sin resultados",
    "dash.noResultsDesc": "No se encontraron negocios para esta búsqueda.",
    "dash.statusQueued": "En cola",
    "dash.statusRunning": "Ejecutando",
    "dash.statusCompleted": "Completado",
    "dash.statusFailed": "Error",
    "dash.statusQueuedDesc": "La búsqueda está en cola, comenzará pronto.",
    "dash.statusRunningDesc": "El scraping está en progreso, espera unos minutos.",
    "dash.statusFailedDesc": "La búsqueda falló. Intenta de nuevo.",
    "dash.colName": "Negocio",
    "dash.colCategory": "Categoría",
    "dash.colPhone": "Teléfono",
    "dash.colWebsite": "Web",
    "dash.colEmail": "Email",
    "dash.colRating": "Rating",
    "dash.quotaError": "Cuota agotada",
    "dash.quotaErrorDesc": "Has alcanzado el límite de leads de tu plan.",
    "dash.searchCreated": "¡Búsqueda creada!",
    "dash.searchCreatedDesc": "El scraping ha comenzado.",
    "dash.searchError": "Error",
    "dash.searchErrorDesc": "No se pudo crear la búsqueda.",
    "dash.apifyNotConfigured": "Conéctate a Apify para activar el scraping automático.",
    "dash.newSearchTitle": "Nueva búsqueda",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>("en");

  const t = (key: string): string => {
    return translations[lang][key] ?? translations["en"][key] ?? key;
  };

  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}
