import { createContext, useContext, useEffect, useState, ReactNode } from "react";

type Lang = "en" | "es";

interface LanguageContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: string) => string;
}

const storageKey = "mapleads-lang";

const translations: Record<Lang, Record<string, string>> = {
  en: {
    "nav.howItWorks": "How it works",
    "nav.pricing": "Pricing",
    "nav.testimonials": "Testimonials",
    "nav.faq": "FAQ",
    "nav.login": "Sign in",
    "nav.cta": "Get started free",

    "hero.badge": "Powered by Google Maps and Apify",
    "hero.headline1": "Find customers in",
    "hero.headline2": "any city",
    "hero.headline3": "in the world",
    "hero.subheadline": "Extract leads from Google Maps with name, phone, address, website, and email in minutes.",
    "hero.stat1": "Businesses indexed",
    "hero.stat2": "Countries available",
    "hero.stat3": "Average scraping time",
    "hero.cta1": "Get started free",
    "hero.cta2": "See how it works",
    "hero.cardCompleted": "Search completed",
    "hero.cardLeads": "leads found",
    "hero.lead": "Lead",
    "hero.sampleSearch": "Restaurants - Barcelona - Spain",

    "problem.title1": "The problem with",
    "problem.title2": "traditional prospecting",
    "problem.subtitle": "Teams waste weeks collecting leads manually. MapLeads solves it in minutes.",
    "problem.withoutTitle": "Without MapLeads",
    "problem.withTitle": "With MapLeads",
    "problem.p1": "Outdated and expensive lead lists",
    "problem.p2": "Incomplete data with missing phone or website",
    "problem.p3": "Limited geographic coverage",
    "problem.p4": "Manual scraping that takes hours",
    "problem.p5": "Per-lead pricing that inflates costs",
    "problem.s1": "Real-time data from Google Maps",
    "problem.s2": "Name, phone, website, and email included",
    "problem.s3": "195+ countries with no geographic restrictions",
    "problem.s4": "Results ready in under 5 minutes",
    "problem.s5": "Flat plans with thousands of included leads",

    "how.title1": "How it works",
    "how.title2": "in 3 steps",
    "how.subtitle": "No setup, no code, no manual copy-paste.",
    "how.step1.title": "Define your search",
    "how.step1.desc": "Enter keyword, city, and country. Example: restaurants, Barcelona, Spain.",
    "how.step2.title": "Automatic extraction",
    "how.step2.desc": "Our engine processes Google Maps and collects business data automatically.",
    "how.step3.title": "Export and execute",
    "how.step3.desc": "Download your leads as CSV and use them in your CRM or outreach workflow.",

    "pricing.title1": "Simple and",
    "pricing.title2": "transparent pricing",
    "pricing.subtitle": "Choose a plan, pay with PayPal, and scale when needed.",
    "pricing.popular": "Most popular",
    "pricing.perMonth": "/month",
    "pricing.leadsMonth": "leads/month",
    "pricing.footer": "Secure PayPal payments. No contracts. Cancel anytime.",
    "pricing.paypal": "Continue with PayPal",
    "pricing.starter.desc": "For freelancers and early-stage teams.",
    "pricing.starter.f1": "2,000 leads per month",
    "pricing.starter.f2": "Unlimited searches",
    "pricing.starter.f3": "CSV export",
    "pricing.starter.f4": "Name, phone, website, and address",
    "pricing.starter.f5": "Email support",
    "pricing.starter.cta": "Start Starter",
    "pricing.growth.desc": "For growing sales operations.",
    "pricing.growth.f1": "5,000 leads per month",
    "pricing.growth.f2": "Everything in Starter",
    "pricing.growth.f3": "Email enrichment included",
    "pricing.growth.f4": "Full search history",
    "pricing.growth.f5": "Priority support",
    "pricing.growth.cta": "Start Growth",
    "pricing.pro.desc": "For agencies and advanced teams.",
    "pricing.pro.f1": "15,000 leads per month",
    "pricing.pro.f2": "Everything in Growth",
    "pricing.pro.f3": "Automated recurring searches",
    "pricing.pro.f4": "API access coming soon",
    "pricing.pro.f5": "Dedicated support",
    "pricing.pro.cta": "Start Pro",

    "testimonials.title1": "Trusted by",
    "testimonials.title2": "real growth teams",
    "testimonials.subtitle": "Stories from professionals using MapLeads every week.",

    "faq.title1": "Frequently",
    "faq.title2": "asked questions",
    "faq.q1": "Where does the data come from?",
    "faq.a1": "MapLeads uses Apify to collect publicly available business data from Google Maps.",
    "faq.q2": "Is it legal to use MapLeads?",
    "faq.a2": "MapLeads extracts public business information. You remain responsible for compliant outreach in your market.",
    "faq.q3": "How long does a search take?",
    "faq.a3": "Most searches complete in 2 to 5 minutes depending on the requested volume.",
    "faq.q4": "What does email enrichment include?",
    "faq.a4": "Growth and Pro plans scan websites to identify public contact emails.",
    "faq.q5": "Can I cancel my subscription?",
    "faq.a5": "Yes. You can cancel anytime and keep access until the end of the billing period.",
    "faq.q6": "Do lead limits reset monthly?",
    "faq.a6": "Yes. Your monthly lead usage resets automatically in each billing cycle.",
    "faq.q7": "How are payments processed?",
    "faq.a7": "All payments are processed securely via PayPal.",

    "cta.title1": "Start generating leads",
    "cta.title2": "today",
    "cta.subtitle": "Join teams using MapLeads to find qualified prospects every day.",
    "cta.btn": "Create free account",
    "cta.footer": "No credit card required to start.",

    "footer.rights": "Copyright 2026 MapLeads. All rights reserved.",
    "footer.privacy": "Privacy",
    "footer.terms": "Terms",

    "auth.back": "Back to home",
    "auth.login": "Sign in",
    "auth.register": "Create account",
    "auth.email": "Email",
    "auth.password": "Password",
    "auth.name": "Full name",
    "auth.namePlaceholder": "Your name",
    "auth.emailPlaceholder": "you@company.com",
    "auth.passwordPlaceholder": "Minimum 6 characters",
    "auth.loginBtn": "Sign in",
    "auth.loginLoading": "Signing in...",
    "auth.registerBtn": "Create free account",
    "auth.registerLoading": "Creating account...",
    "auth.terms1": "By registering you accept our",
    "auth.termsLink": "Terms of service",
    "auth.terms2": "and",
    "auth.privacyLink": "Privacy policy",
    "auth.loginError": "Sign in error",
    "auth.registerSuccess": "Account created",
    "auth.registerSuccessDesc": "Check your inbox to confirm your account.",
    "auth.registerError": "Registration error",

    "dash.title": "Dashboard",
    "dash.subtitle": "Manage your searches and leads",
    "dash.newSearch": "New search",
    "dash.searches": "Searches",
    "dash.leadsUsed": "Leads used",
    "dash.upgradeBtn": "Upgrade plan",
    "dash.signOut": "Sign out",
    "dash.emptyTitle": "No searches yet",
    "dash.emptyCreate": "Create your first search",
    "dash.keyword": "Keyword",
    "dash.keywordPlaceholder": "restaurants, dentists, lawyers...",
    "dash.city": "City",
    "dash.cityPlaceholder": "Barcelona",
    "dash.country": "Country",
    "dash.countryPlaceholder": "Spain",
    "dash.maxResults": "Maximum results",
    "dash.quotaAvailable": "Available quota",
    "dash.startSearch": "Start search",
    "dash.starting": "Starting...",
    "dash.cancel": "Cancel",
    "dash.exportCsv": "Export CSV",
    "dash.welcomeTitle": "Welcome to MapLeads",
    "dash.welcomeDesc": "Create your first search to extract leads from Google Maps in any city.",
    "dash.createFirst": "Create first search",
    "dash.noResults": "No results",
    "dash.noResultsDesc": "No businesses were found for this search.",
    "dash.statusQueued": "Queued",
    "dash.statusRunning": "Running",
    "dash.statusCompleted": "Completed",
    "dash.statusFailed": "Failed",
    "dash.statusQueuedDesc": "The search is queued and will start soon.",
    "dash.statusRunningDesc": "Scraping is in progress. Please wait a few minutes.",
    "dash.statusFailedDesc": "The search failed. Please try again.",
    "dash.colName": "Business",
    "dash.colCategory": "Category",
    "dash.colPhone": "Phone",
    "dash.colWebsite": "Website",
    "dash.colEmail": "Email",
    "dash.colRating": "Rating",
    "dash.colAddress": "Address",
    "dash.quotaError": "Quota exhausted",
    "dash.quotaErrorDesc": "You reached your lead limit for the current plan.",
    "dash.searchCreated": "Search created",
    "dash.searchCreatedDesc": "Scraping has started.",
    "dash.searchError": "Error",
    "dash.searchErrorDesc": "The search could not be created.",
    "dash.apifyNotConfigured": "Connect Apify to activate automatic scraping.",
    "dash.newSearchTitle": "New search",
    "dash.detailsMeta": "max",
    "dash.superAdmin": "Superadmin panel",
    "dash.suspendedTitle": "Account suspended",
    "dash.suspendedDesc": "Your account has been suspended. Contact support for access.",

    "admin.title": "Superadmin Panel",
    "admin.subtitle": "User management",
    "admin.back": "Back to dashboard",
    "admin.searchPlaceholder": "Search by email or name...",
    "admin.refresh": "Refresh",
    "admin.colUser": "User",
    "admin.colPlan": "Plan",
    "admin.colUsage": "Usage",
    "admin.colStatus": "Status",
    "admin.colActions": "Actions",
    "admin.active": "Active",
    "admin.suspended": "Suspended",
    "admin.noUsers": "No users found.",
    "admin.savePlan": "Save plan",
    "admin.suspend": "Suspend",
    "admin.restore": "Restore",
    "admin.delete": "Delete",
    "admin.confirmDelete": "This will permanently delete the user and all related data. Continue?",
    "admin.unauthorized": "Only afiliadosprobusiness@gmail.com can access this panel.",
    "admin.accessRule": "Superadmin allowlist email",
    "admin.actionSuccess": "Action completed",
    "admin.actionError": "Action failed",

    "notFound.message": "Page not found",
    "notFound.back": "Return to home",
  },
  es: {
    "nav.howItWorks": "Como funciona",
    "nav.pricing": "Precios",
    "nav.testimonials": "Testimonios",
    "nav.faq": "FAQ",
    "nav.login": "Iniciar sesion",
    "nav.cta": "Empezar gratis",

    "hero.badge": "Impulsado por Google Maps y Apify",
    "hero.headline1": "Encuentra clientes en",
    "hero.headline2": "cualquier ciudad",
    "hero.headline3": "del mundo",
    "hero.subheadline": "Extrae leads de Google Maps con nombre, telefono, direccion, web y email en minutos.",
    "hero.stat1": "Negocios indexados",
    "hero.stat2": "Paises disponibles",
    "hero.stat3": "Tiempo promedio de scraping",
    "hero.cta1": "Empezar gratis",
    "hero.cta2": "Ver como funciona",
    "hero.cardCompleted": "Busqueda completada",
    "hero.cardLeads": "leads encontrados",
    "hero.lead": "Lead",
    "hero.sampleSearch": "Restaurantes - Barcelona - Espana",

    "problem.title1": "El problema de la",
    "problem.title2": "prospeccion tradicional",
    "problem.subtitle": "Los equipos pierden semanas buscando leads manualmente. MapLeads lo resuelve en minutos.",
    "problem.withoutTitle": "Sin MapLeads",
    "problem.withTitle": "Con MapLeads",
    "problem.p1": "Listas desactualizadas y costosas",
    "problem.p2": "Datos incompletos sin telefono o web",
    "problem.p3": "Cobertura geografica limitada",
    "problem.p4": "Scraping manual que toma horas",
    "problem.p5": "Cobro por lead que eleva costos",
    "problem.s1": "Datos en tiempo real desde Google Maps",
    "problem.s2": "Nombre, telefono, web y email incluidos",
    "problem.s3": "195+ paises sin restricciones geograficas",
    "problem.s4": "Resultados listos en menos de 5 minutos",
    "problem.s5": "Planes fijos con miles de leads incluidos",

    "how.title1": "Como funciona",
    "how.title2": "en 3 pasos",
    "how.subtitle": "Sin configuraciones, sin codigo, sin trabajo manual.",
    "how.step1.title": "Define tu busqueda",
    "how.step1.desc": "Ingresa keyword, ciudad y pais. Ejemplo: restaurantes, Barcelona, Espana.",
    "how.step2.title": "Extraccion automatica",
    "how.step2.desc": "Nuestro motor procesa Google Maps y recopila datos de negocios automaticamente.",
    "how.step3.title": "Exporta y ejecuta",
    "how.step3.desc": "Descarga tus leads en CSV y usalos en tu CRM o flujo comercial.",

    "pricing.title1": "Precios simples y",
    "pricing.title2": "transparentes",
    "pricing.subtitle": "Elige un plan, paga con PayPal y escala cuando lo necesites.",
    "pricing.popular": "Mas popular",
    "pricing.perMonth": "/mes",
    "pricing.leadsMonth": "leads/mes",
    "pricing.footer": "Pagos seguros con PayPal. Sin contratos. Cancela cuando quieras.",
    "pricing.paypal": "Continuar con PayPal",
    "pricing.starter.desc": "Para freelancers y equipos en etapa inicial.",
    "pricing.starter.f1": "2,000 leads por mes",
    "pricing.starter.f2": "Busquedas ilimitadas",
    "pricing.starter.f3": "Exportacion CSV",
    "pricing.starter.f4": "Nombre, telefono, web y direccion",
    "pricing.starter.f5": "Soporte por email",
    "pricing.starter.cta": "Comenzar Starter",
    "pricing.growth.desc": "Para equipos de ventas en crecimiento.",
    "pricing.growth.f1": "5,000 leads por mes",
    "pricing.growth.f2": "Todo lo de Starter",
    "pricing.growth.f3": "Email enrichment incluido",
    "pricing.growth.f4": "Historial completo de busquedas",
    "pricing.growth.f5": "Soporte prioritario",
    "pricing.growth.cta": "Comenzar Growth",
    "pricing.pro.desc": "Para agencias y equipos avanzados.",
    "pricing.pro.f1": "15,000 leads por mes",
    "pricing.pro.f2": "Todo lo de Growth",
    "pricing.pro.f3": "Busquedas recurrentes automaticas",
    "pricing.pro.f4": "Acceso API proximamente",
    "pricing.pro.f5": "Soporte dedicado",
    "pricing.pro.cta": "Comenzar Pro",

    "testimonials.title1": "Confiado por",
    "testimonials.title2": "equipos reales",
    "testimonials.subtitle": "Historias de profesionales que usan MapLeads cada semana.",

    "faq.title1": "Preguntas",
    "faq.title2": "frecuentes",
    "faq.q1": "De donde vienen los datos?",
    "faq.a1": "MapLeads usa Apify para recopilar datos publicos de negocios en Google Maps.",
    "faq.q2": "Es legal usar MapLeads?",
    "faq.a2": "MapLeads extrae informacion publica. El usuario es responsable de cumplir normativas de outreach.",
    "faq.q3": "Cuanto tarda una busqueda?",
    "faq.a3": "La mayoria de busquedas se completa en 2 a 5 minutos segun volumen solicitado.",
    "faq.q4": "Que incluye email enrichment?",
    "faq.a4": "Los planes Growth y Pro escanean sitios web para identificar correos de contacto publicos.",
    "faq.q5": "Puedo cancelar mi suscripcion?",
    "faq.a5": "Si. Puedes cancelar en cualquier momento y mantienes acceso hasta el fin del ciclo.",
    "faq.q6": "La cuota se reinicia cada mes?",
    "faq.a6": "Si. El uso mensual de leads se reinicia automaticamente cada ciclo de facturacion.",
    "faq.q7": "Como se procesan los pagos?",
    "faq.a7": "Todos los pagos se procesan de forma segura con PayPal.",

    "cta.title1": "Empieza a generar leads",
    "cta.title2": "hoy",
    "cta.subtitle": "Unete a equipos que usan MapLeads para encontrar prospectos calificados cada dia.",
    "cta.btn": "Crear cuenta gratis",
    "cta.footer": "No se requiere tarjeta para empezar.",

    "footer.rights": "Copyright 2026 MapLeads. Todos los derechos reservados.",
    "footer.privacy": "Privacidad",
    "footer.terms": "Terminos",

    "auth.back": "Volver al inicio",
    "auth.login": "Iniciar sesion",
    "auth.register": "Crear cuenta",
    "auth.email": "Email",
    "auth.password": "Contrasena",
    "auth.name": "Nombre completo",
    "auth.namePlaceholder": "Tu nombre",
    "auth.emailPlaceholder": "tu@empresa.com",
    "auth.passwordPlaceholder": "Minimo 6 caracteres",
    "auth.loginBtn": "Iniciar sesion",
    "auth.loginLoading": "Iniciando sesion...",
    "auth.registerBtn": "Crear cuenta gratis",
    "auth.registerLoading": "Creando cuenta...",
    "auth.terms1": "Al registrarte aceptas nuestros",
    "auth.termsLink": "Terminos del servicio",
    "auth.terms2": "y",
    "auth.privacyLink": "Politica de privacidad",
    "auth.loginError": "Error al iniciar sesion",
    "auth.registerSuccess": "Cuenta creada",
    "auth.registerSuccessDesc": "Revisa tu correo para confirmar la cuenta.",
    "auth.registerError": "Error al registrarse",

    "dash.title": "Dashboard",
    "dash.subtitle": "Gestiona tus busquedas y leads",
    "dash.newSearch": "Nueva busqueda",
    "dash.searches": "Busquedas",
    "dash.leadsUsed": "Leads usados",
    "dash.upgradeBtn": "Actualizar plan",
    "dash.signOut": "Cerrar sesion",
    "dash.emptyTitle": "No tienes busquedas",
    "dash.emptyCreate": "Crea tu primera busqueda",
    "dash.keyword": "Keyword",
    "dash.keywordPlaceholder": "restaurantes, dentistas, abogados...",
    "dash.city": "Ciudad",
    "dash.cityPlaceholder": "Barcelona",
    "dash.country": "Pais",
    "dash.countryPlaceholder": "Espana",
    "dash.maxResults": "Maximo de resultados",
    "dash.quotaAvailable": "Cuota disponible",
    "dash.startSearch": "Iniciar busqueda",
    "dash.starting": "Iniciando...",
    "dash.cancel": "Cancelar",
    "dash.exportCsv": "Exportar CSV",
    "dash.welcomeTitle": "Bienvenido a MapLeads",
    "dash.welcomeDesc": "Crea tu primera busqueda para extraer leads de Google Maps en cualquier ciudad.",
    "dash.createFirst": "Crear primera busqueda",
    "dash.noResults": "Sin resultados",
    "dash.noResultsDesc": "No se encontraron negocios para esta busqueda.",
    "dash.statusQueued": "En cola",
    "dash.statusRunning": "Ejecutando",
    "dash.statusCompleted": "Completado",
    "dash.statusFailed": "Fallido",
    "dash.statusQueuedDesc": "La busqueda esta en cola y comenzara pronto.",
    "dash.statusRunningDesc": "El scraping esta en progreso. Espera unos minutos.",
    "dash.statusFailedDesc": "La busqueda fallo. Intenta nuevamente.",
    "dash.colName": "Negocio",
    "dash.colCategory": "Categoria",
    "dash.colPhone": "Telefono",
    "dash.colWebsite": "Web",
    "dash.colEmail": "Email",
    "dash.colRating": "Rating",
    "dash.colAddress": "Direccion",
    "dash.quotaError": "Cuota agotada",
    "dash.quotaErrorDesc": "Alcanzaste el limite de leads de tu plan.",
    "dash.searchCreated": "Busqueda creada",
    "dash.searchCreatedDesc": "El scraping ha comenzado.",
    "dash.searchError": "Error",
    "dash.searchErrorDesc": "No se pudo crear la busqueda.",
    "dash.apifyNotConfigured": "Conecta Apify para activar el scraping automatico.",
    "dash.newSearchTitle": "Nueva busqueda",
    "dash.detailsMeta": "max",
    "dash.superAdmin": "Panel superadmin",
    "dash.suspendedTitle": "Cuenta suspendida",
    "dash.suspendedDesc": "Tu cuenta fue suspendida. Contacta soporte para recuperar acceso.",

    "admin.title": "Panel Superadmin",
    "admin.subtitle": "Gestion de usuarios",
    "admin.back": "Volver al dashboard",
    "admin.searchPlaceholder": "Buscar por email o nombre...",
    "admin.refresh": "Actualizar",
    "admin.colUser": "Usuario",
    "admin.colPlan": "Plan",
    "admin.colUsage": "Uso",
    "admin.colStatus": "Estado",
    "admin.colActions": "Acciones",
    "admin.active": "Activo",
    "admin.suspended": "Suspendido",
    "admin.noUsers": "No se encontraron usuarios.",
    "admin.savePlan": "Guardar plan",
    "admin.suspend": "Suspender",
    "admin.restore": "Restaurar",
    "admin.delete": "Eliminar",
    "admin.confirmDelete": "Esto eliminara al usuario y todos sus datos de forma permanente. Continuar?",
    "admin.unauthorized": "Solo afiliadosprobusiness@gmail.com puede acceder a este panel.",
    "admin.accessRule": "Email en allowlist superadmin",
    "admin.actionSuccess": "Accion completada",
    "admin.actionError": "La accion fallo",

    "notFound.message": "Pagina no encontrada",
    "notFound.back": "Volver al inicio",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLang] = useState<Lang>(() => {
    if (typeof window === "undefined") return "en";
    const saved = window.localStorage.getItem(storageKey);
    return saved === "es" ? "es" : "en";
  });

  useEffect(() => {
    if (typeof window !== "undefined") {
      window.localStorage.setItem(storageKey, lang);
    }
  }, [lang]);

  const t = (key: string): string => translations[lang][key] ?? translations.en[key] ?? key;

  return <LanguageContext.Provider value={{ lang, setLang, t }}>{children}</LanguageContext.Provider>;
}

export function useLang() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLang must be used within LanguageProvider");
  return ctx;
}

